on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  
name: CI

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          components: rustfmt, clippy
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        name: Check Code Format 🔧
        with:
          command: fmt
          args: -- --check
      - uses: actions-rs/cargo@v1
        name: Running Tests 🚀
        env:
          RUST_BACKTRACE: full
        with:
          command: test
          args: --all-features --workspace
  bench:
    name: Build and Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-bench
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          components: rustfmt, clippy
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        name: Benchmark 🚀
        with:
          command: bench
          args: --all-features --workspace
